feature/PP-45
rsksmart/rif-relay-client pull request #22
Opened 2022-07-13 21:45 UTC by franciscotobar

## What

- Solve circular dependency found when including unit tests in rif-relay-contracts
- Add unit testing for each dependency for the Rif Relay Project

## Why

- Circular dependencies must be avoided in most of the situations
- Each project needs to have their own way of testing

## Refs

- https://rsklabs.atlassian.net/browse/PP-45
- https://rsklabs.atlassian.net/browse/PP-236

2022-07-18 11:47 UTC, antomor requested changes
Although the tests are running properly, I think we have some build issues. Could you please review them?

2022-07-18 11:47 UTC, antomor commented on src/Configurator.ts
> +    console.log('-------------------------------');
Could we remove those log lines?

2022-07-18 11:47 UTC, antomor commented on src/RelayClient.ts
> +            console.log('si llegue aca bien y sin novedad2');
I think this line could be removed

2022-07-18 11:47 UTC, antomor commented on src/RelayClient.ts
> +            console.log('si llegue aca bien y sin novedad3');
I think this line could be removed

2022-07-18 11:47 UTC, antomor commented on src/RelayClient.ts
> +        console.log(' si estamos pasando x aca ');
I think this line could be removed

2022-07-18 13:46 UTC, franciscotobar commented on src/Configurator.ts
> +    console.log('-------------------------------');
sure, Ill remove it.

2022-07-22 12:35 UTC, antomor commented on package.json
> +    "@rsksmart/rif-relay-common": "github:rsksmart/rif-relay-common#feature/PP-45",
we should update those lines before merging the PR

2022-07-29 08:28 UTC, antomor approved these changes
LGTM

2022-07-29 08:29 UTC, merged