feature/PP-240
rsksmart/rif-relay-client pull request #23
Opened 2022-07-21 13:51 UTC by franciscotobar

## What

- Validation for smart wallet address to verify if it belongs to the EOA and its deployed

## Why

- To be able to import a smart wallet

## Refs

- [Jira issue](https://rsklabs.atlassian.net/browse/PP-204)
- https://github.com/rsksmart/rif-relay-common/pull/23

2022-08-04 10:40 UTC, antomor requested changes
@franciscotobar Apart from the comment, I think that here we are testing for the method implementation. I mean, if we test that all inner objects are called, we'll probably need to change all those tests if we change the method implementation. IMHO we should at least include all these checks in one single test, because after all, we're testing for its flow, so we need all of them to be checked. So in summary, I think we could check all the method calls in one single test.
However, if someone from @rsksmart/payments has different opinions, I'd be glad to hear.

2022-08-04 10:40 UTC, antomor commented on test/RelayClient.test.ts
> +            expect(fakeContractInteractor.getSenderNonce).to.have.been.called;
we're not checking how many times the method has been called

2022-08-04 10:40 UTC, antomor commented on test/RelayClient.test.ts
> +            expect(fakeAccountManager.sign).to.have.been.called;
we're not checking how many times the method has been called

2022-08-04 10:40 UTC, antomor commented on test/RelayClient.test.ts
> +            expect(fakeContractInteractor.verifyForwarder).to.have.been.called;
we're not checking how many times the method has been called

2022-08-09 16:51 UTC, AndresQuijano approved these changes
LGTM

2022-08-12 16:14 UTC, antomor approved these changes
LGTM

2022-08-12 16:14 UTC, merged